# Generated by Django 4.2.30 on 2026-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
