# Generated by Django 4.2.30 on 2026-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='store_produ_title_244706_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
    ]
